apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: ghcr.io/ruthw-ssi/springboot
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  labels:
    app: springboot-service
spec:
  selector:
    app: springboot
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP