apiVersion: apps/v1
kind: Deployment
metadata:
  name: user01RW
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user01RW
  template:
    metadata:
      labels:
        app: user01RW
    spec:
      containers:
        - name: springboot
          image: ghcr.io/ruthw-ssi/springboot
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user01RW
  labels:
    app: user01RW
spec:
  selector:
    app: user01RW
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP